services:
  postgres_snapshots:
    image: postgres:latest
    environment:
      POSTGRES_DB: snapshots_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./sql/snapshots_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_network
    ports:
      - "5432:5432"

  postgres_metadata:
    image: postgres:latest
    environment:
      POSTGRES_DB: metadata_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./sql/metadata_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_network
    ports:
      - "5431:5432"

  prometheus-pushgateway:
    image: prom/pushgateway
    container_name: prometheus-pushgateway
    ports:
      - "9091:9091"
    networks:
      - prometheus_network

  prometheus-server:
    image: prom/prometheus
    container_name: prometheus-server
    depends_on:
      - prometheus-pushgateway
    ports:
      - "9090:9090"
    networks:
      - prometheus_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  snapshots:
    environment:
      SNAPSHOTS_DB_USERNAME: myuser
      SNAPSHOTS_DB_PASSWORD: mypassword
      METADATA_DB_USERNAME: myuser
      METADATA_DB_PASSWORD: mypassword
      METADATA_DB_HOST: postgres_metadata
      METADATA_DB_PORT: 5432
      PROMETHEUS_GATEWAY_URL: prometheus-pushgateway:9091
    build:
      .
    stdin_open: true
    container_name: snapshots
    depends_on:
      - prometheus-pushgateway
      - postgres_metadata
      - postgres_snapshots
    networks:
      - prometheus_network
      - postgres_network
    volumes:
      - ./data:/data


networks:
  prometheus_network:
    driver: bridge
  postgres_network:
    driver: bridge